### PR TITLE
Add build options for MOAB dependency

### PR DESCRIPTION
**Pull request by gonuke**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Try including MOAB as an optional build dependency.  It may work but probably isn't best practice...

### CODE REVIEW

**Comment by gonuke** [comment]
@conda-forge-admin , please rerender

**Comment by gonuke** [comment]
@conda-forge-admin , please rerender

**Comment by bam241** [comment]
LGTM!

Let me know when this is ready for a final review.

**Comment by bam241** [comment]
seems to be finding MOAB in cmake:
```
-- MOAB Found: TRUE
-- Found MOAB: $PREFIX/lib/libMOAB.so  
-- MOAB header files: $PREFIX/include
-- MOAB library: $PREFIX/lib/libMOAB.so
```

**Pull request merged**
