### PR TITLE
[WIP] Fixing PyNE conda forge

### PR DESCRIPTION
**Pull request by bam241**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by kkiesling** [comment]
This PR can be closed as all changes have been merged into CNERG/pyne-feedstock and are included in #34

**Comment by bam241** [comment]
Hey, 

@conda-forge-admin, please rerender

**Comment by bam241** [comment]
Hey,

@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by bam241** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
@bam241 What's the state of this PR?

**Comment by CJ-Wright** [comment]
@scopatz ?

**Comment by bam241** [comment]
I was waiting on the other Pyne-feesstock PR to be merged.

I am also waiting on some other package to be in conda forge to continue this.

**Comment by scopatz** [comment]
Is this still WIP?

**Pull request merged**
