### PR TITLE
Change this config to run from the branch

### PR DESCRIPTION
**Pull request by gonuke**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Change this config to run from the branch instead of the tag so that we can test as it is updated.

### CODE REVIEW

**Comment by gonuke** [comment]
@conda-forge-admin , please rerender

**Comment by gonuke** [comment]
@conda-forge-admin , please rerender

**Comment by bam241** [comment]
this looks good to me,
thx @gonuke 
merging.

**Comment by gonuke** [comment]
Except the sha for the branch is changing often... maybe it's not a great plan???

**Pull request merged**
