### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
The unit tests for this package are failing from what looks like to me like missing test data.  Perhaps the download location changed?  Can the feedstock maintainer have a look at this?  I do not know enough about the package to debug this issue.

**Comment by scopatz** [comment]
Thanks for this @jjhelmus - One of our data providers went down.  We have a fix in pyne but we are having other problems building.  We'll be sure to include this change set when we update the feedstock for the next version.

**Comment by jjhelmus** [comment]
Waiting for a new version for a long prefix build sounds fine by me.  Feel free to close this PR if you wish, or keep in open as a reminder.

**Comment by scopatz** [comment]
Yeah, let's leave it open as a reminder :).

**Comment by jakirkham** [comment]
Is this still blocked, @scopatz? Was just noticing that PR ( https://github.com/conda-forge/pyne-feedstock/pull/8 ), which was added recently, built without issue.

**Comment by scopatz** [comment]
This conflicts with master now since I merged #8. I think #8 might have implemented this, though.  It might be OK to close this.

**Pull request closed without merging**
